# Example = [auth, econ, culture]
## right-wing idelogies
classical_liberalism = [-7.5, 6.5, -13]
conservatism = []
libertarianism = []
economic_liberalism = []
monarchism = []
nationalism = []
neoliberalism = []
right_libertarianism = []
traditionalism = []
social_conservatism = []
economic_conservatism = []
cultural_conservatism = []
religious_conservatism = []
tea_party = []
auth_cap = []
ancap = []
rw_populism = []
market_conservatism = []
economic_nationalism = []
## left-wing ideologies
socialism = []
progressivism = []
social_democracy = []
communism = []
anarchism = []
eco_socialism = []

